# Generated by Django 3.2.16 on 2022-11-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_workout_app', '0002_exercise_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcategory',
            name='featured_image',
        ),
    ]
